# Coded by Domo4862
# Mad libs referenced from (http://www.madlibs.com/content/uploads/2016/04/VacationFun_ML_2009_pg15.pdf)
# Similar game style to Cards Against Humanities

print("This is a Mad Libs Generator made with Python 3.6.1.")
print("Fill in the words when prompted. You are allowed to go wild.")
print("Total Input required = 19")
print("")

a = input("Adjective:")
b = input("Adjective:")
c = input("Noun:")
d = input("Noun:")
e = input("Plural Noun:")
f = input("Game:")
g = input("Plural Noun:")
h = input("Verb Ending in 'ing':")
i = input("Verb ending in 'ing':")
j = input("Plural Noun:")
k = input("Verb ending in 'ing':")
l = input("Noun:")
m = input("Plant:")
n = input("Part of the Body:")
o = input("A Place:")
p = input("Verb ending in 'ing':")
q = input("Adjective:")
r = input("Number:")
s = input("Plural Noun:")

print("")
print("A Vacation is when you take a trip to some {} place with your {} family.".format(a,b))
print("Usually you go to some place that is near a/an {} or up on a/an {}.".format(c, d))
print("A good vacation place is one where you can ride {} or play {} or go hunting for {}.".format(e, f, g))
print("I like to spend my time {} or {}.".format(h, i))
print("When parents go on a vacation, they spend their time eating three {} a day, and fathers play golf, and mothers sit around {}.".format(j, k))
print("Last summer, my little borther fell in a/an {} and got poison {} all over his {}.".format(l, m, n))
print("My family is going to go to (the) {}, and I will practice {}.".format(o, p))
print("Parents need vacations more than kids because paretns are always very {} and because\
they have to work {} hours every day making enough {} to pay for the vacation.".format(q, r, s))